import { toResult } from '@/constants/utils'

const mockUserInfo = {
  isLogin: true,
  email_verified: 1,
  face: 'https://i0.hdslb.com/bfs/face/0c84b9f4ad546d3f20324809d45fc439a2a8ddab.jpg',
  face_nft: 0,
  face_nft_type: 0,
  level_info: {
    current_level: 6,
    current_min: 28800,
    current_exp: 29050,
    next_exp: '--',
  },
  mid: 3493281916783362,
  mobile_verified: 1,
  money: 9999.99,
  moral: 70,
  official: {
    role: 0,
    title: '',
    desc: '',
    type: -1,
  },
  officialVerify: {
    type: -1,
    desc: '',
  },
  pendant: {
    pid: 0,
    name: '',
    image: '',
    expire: 0,
    image_enhance: '',
    image_enhance_frame: '',
    n_pid: 0,
  },
  scores: 0,
  uname: 'bilibili',
  vipDueDate: 1674748800000,
  vipStatus: 0,
  vipType: 1,
  vip_pay_type: 0,
  vip_theme_type: 0,
  vip_label: {
    path: '',
    text: '',
    label_theme: '',
    text_color: '',
    bg_style: 0,
    bg_color: '',
    border_color: '',
    use_img_label: true,
    img_label_uri_hans: '',
    img_label_uri_hant: '',
    img_label_uri_hans_static: '',
    img_label_uri_hant_static: '',
  },
  vip_avatar_subscript: 0,
  vip_nickname_color: '',
  vip: {
    type: 1,
    status: 0,
    due_date: 1674748800000,
    vip_pay_type: 0,
    theme_type: 0,
    label: {
      path: '',
      text: '',
      label_theme: '',
      text_color: '',
      bg_style: 0,
      bg_color: '',
      border_color: '',
      use_img_label: true,
      img_label_uri_hans: '',
      img_label_uri_hant: '',
      img_label_uri_hans_static: '',
      img_label_uri_hant_static: '',
    },
    avatar_subscript: 0,
    nickname_color: '',
    role: 0,
    avatar_subscript_url: '',
    tv_vip_status: 0,
    tv_vip_pay_type: 0,
    tv_due_date: 0,
    avatar_icon: {
      icon_resource: {},
    },
  },
  wallet: {
    mid: 3493281916783362,
    bcoin_balance: 0,
    coupon_balance: 0,
    coupon_due_time: 0,
  },
  has_shop: false,
  shop_url: '',
  answer_status: 0,
  is_senior_member: 1,
  wbi_img: {
    img_url: '',
    sub_url: '',
  },
  is_jury: false,
  name_render: null,
}

export const mockUserInfoResult = toResult(mockUserInfo)
