import { toResult } from '@/constants/utils'

const mockUserInfo = {
  profile: {
    mid: 3493281916783362,
    name: 'bilibili',
    sex: '保密',
    face: 'https://i0.hdslb.com/bfs/face/0c84b9f4ad546d3f20324809d45fc439a2a8ddab.jpg',
    sign: '',
    rank: 10000,
    level: 6,
    jointime: 0,
    moral: 70,
    silence: 0,
    email_status: 0,
    tel_status: 1,
    identification: 0,
    vip: {
      type: 0,
      status: 0,
      due_date: 0,
      vip_pay_type: 0,
      theme_type: 0,
      label: {
        path: '',
        text: '',
        label_theme: '',
        text_color: '',
        bg_style: 0,
        bg_color: '',
        border_color: '',
        use_img_label: true,
        img_label_uri_hans: '',
        img_label_uri_hant: '',
        img_label_uri_hans_static: 'https://i0.hdslb.com/bfs/vip/d7b702ef65a976b20ed854cbd04cb9e27341bb79.png',
        img_label_uri_hant_static:
          'https://i0.hdslb.com/bfs/activity-plat/static/20220614/e369244d0b14644f5e1a06431e22a4d5/KJunwh19T5.png',
        label_id: 0,
        label_goto: null,
      },
      avatar_subscript: 0,
      nickname_color: '',
      role: 0,
      avatar_subscript_url: '',
      tv_vip_status: 0,
      tv_vip_pay_type: 0,
      tv_due_date: 0,
      avatar_icon: {
        icon_resource: {},
      },
      ott_info: {
        vip_type: 0,
        pay_type: 0,
        pay_channel_id: '',
        status: 0,
        overdue_time: 0,
      },
      super_vip: {
        is_super_vip: false,
      },
    },
    pendant: {
      pid: 0,
      name: '',
      image: '',
      expire: 0,
      image_enhance: '',
      image_enhance_frame: '',
      n_pid: 0,
    },
    nameplate: {
      nid: 0,
      name: '',
      image: '',
      image_small: '',
      level: '',
      condition: '',
    },
    official: {
      role: 0,
      title: '',
      desc: '',
      type: -1,
    },
    birthday: 315504000,
    is_tourist: 0,
    is_fake_account: 0,
    pin_prompting: 0,
    is_deleted: 0,
    in_reg_audit: 0,
    is_rip_user: false,
    profession: {
      id: 0,
      name: '',
      show_name: '',
      is_show: 0,
      category_one: '',
      realname: '',
      title: '',
      department: '',
      certificate_no: '',
      certificate_show: false,
    },
    face_nft: 0,
    face_nft_new: 0,
    is_senior_member: 0,
    honours: {
      mid: 3493281916783362,
      colour: {
        dark: '#CE8620',
        normal: '#F0900B',
      },
      tags: null,
      is_latest_100honour: 0,
    },
    digital_id: '',
    digital_type: -2,
    attestation: {
      type: 0,
      common_info: {
        title: '',
        prefix: '',
        prefix_title: '',
      },
      splice_info: {
        title: '',
      },
      icon: '',
      desc: '',
    },
    expert_info: {
      title: '',
      state: 0,
      type: 0,
      desc: '',
    },
    name_render: null,
    country_code: '86',
    handle: '',
  },
  level_exp: {
    current_level: 6,
    current_min: 28800,
    current_exp: 29050,
    next_exp: '--',
  },
  coins: 9999.99,
  following: 0,
  follower: 0,
}

const SPACE = {
  USER_INFO: toResult(mockUserInfo),
}
export default SPACE
